### ISSUE TITLE
validateRDBESDataObject- what are we validating?

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBEScore#121]
We agree we don't want to mimic the RDBES data validation. 

We need to document what we validate.

Possibility to only validate needed fields, so our function don't break when a new data model is launched

Possibility to add own fields e.g. for domain estimation.

**Comment by davidcurrie2001** [comment]
There was a suggestion to add a "strict" parameter: if strict = TRUE then all columns are required, if strict = FALSE then only essential columns are required.

**Comment by davidcurrie2001** [comment]
validateRDBESDataObject() validates the structure of the object, but doesn't check its contents e.g. it would be possible for an object to pass the validation but contain values that aren't allowed.  In most cases the RDBES data that is used to create an RDBESDataObject has previously been submitted to ICES so will have already passed the ICES validation checks - we don't duplicate those checks.  Closing issue - re-open if needed.
