### ISSUE TITLE
generateZerosUsingSL() is creating unnecessary extra rows

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#125]
@nmprista The tests in test-generateZerosUsingSL.R are failing because generateZerosUsingSL() is adding an unnecessary extra SA row for LAN even though a relevant LAN row already exists in the SA data.

**Comment by nmprista** [comment]
this should be fixed (tests now pass) but still a warning @davidcurrie2001

**Comment by KirstenBirchHaakansson** [comment]
it still add too many lines, see attachement
[testing_generateZerosUsingSL.pdf](https://github.com/ices-tools-dev/RDBEScore/files/13040549/testing_generateZerosUsingSL.pdf)

**Comment by KirstenBirchHaakansson** [comment]
See scripts at ...\RDBEScore\WGRDBES-EST\personal\Kirsten\testing_generateZerosUsingSL.rmd
