### ISSUE TITLE
generateZerosUsingSL - needs to use the rigth SL

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBEScore#128]
The function needs to pick the right species list (SL)

join SL to data per UK - these will be in SD and SS, then get the SL per SSid.

It looks like all hierarchies have a direct link between SS and SA, also H7 when there is a LE(-) in the upload file between the two recTypes The SS table can only have SS as parent in the present data model.

**Comment by nmprista** [comment]
Seems to be working thus far. If something else found needed, please produce an example that fails expected behavior.
