### ISSUE TITLE
data.table related warning in generateZerosUsingSL

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#132]
there is a data.table warning related to selfreferencing in tests 

`test_file("tests/testthat/test-generateZerosUsingSL.R")`
![image](https://github.com/ices-tools-dev/RDBEScore/assets/31890653/d225e424-ddcf-4f76-a36f-bea174ab7ac2)

**Comment by davidcurrie2001** [comment]
The tests are currently passing and not generating this warning.  Closing issue - re-open if the warning message re-appears.
