### ISSUE TITLE
RDS test files in testthat folder

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/RDBEScore#134]
When these are loaded the `LEid` column in several tables (SA, FT, probably others) is class `logical` not `integer`. 
Causes issues in tests when comparing to downloaded versions.

**Comment by davidcurrie2001** [comment]
H1_2023_10_16.rds has been updated.

**Comment by nicholascarey** [comment]
Yes it's also `h1_RDBESDataObject.rds` and `h1_rdbesRawObject.rds`

**Comment by davidcurrie2001** [comment]
I could only see those files in the previous data format folder "h1_v_1_19_13" so didn't bother with them.  Are they still used anywhere?

**Comment by nicholascarey** [comment]
Ah sorry. Never mind!
