### ISSUE TITLE
Which are the "essential" fields that must always be in the RDBESDataObject?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#140]
Which are the "essential" fields that must always be in the RDBESDataObject?  (These are the fields that are checked for when strict = FALSE is used as a parameter.)

Currently I have said the following are essential:
- All DE and SD fields are essential
- xxID fields are essential
- recType fields are essential
- design variables are essential

The essential fields are defined in the getRDBESDataModelColumnNames.R script in data-raw which creates the mapColNamesFieldR object.

**Comment by nmprista** [comment]
maybe also SL and VD fields?

**Comment by davidcurrie2001** [comment]
I think I also need to include all SS cols.

**Comment by davidcurrie2001** [comment]
> maybe also SL and VD fields?

I'll add in the SL fields.  
@nmprista  Do you think all the VD fields are always required?

**Comment by nmprista** [comment]
@davidcurrie2001 I think enough to consider "essential" fields of VD the mandatory fields of that table.

**Comment by davidcurrie2001** [comment]
Ok, done

**Comment by davidcurrie2001** [comment]
Closing this issue - re-open if we need to add more essential fields.
