### ISSUE TITLE
function that fetches aphiaID available in ICES codelists

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#146]
This function should go into data-raw. When run it should download the aphiaID existing in icesVocab. That download will later be used in creating a data object that contains the taxonomic trees needed for some data preparation.

see icesVocab - https://cran.r-project.org/web/packages/icesVocab/icesVocab.pdf

**Comment by davidcurrie2001** [comment]
The script getICESAphiaIds.R in data-raw downloads the SpecWoRMS code list data and saves it to the package data as **icesSpecWoRMS**.
