### ISSUE TITLE
generateZerosUsingSL - SSuseForCalculateZero needs to be included

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBEScore#151]
If SSuseForCalculateZero == N, then a warning / stop

**Comment by KirstenBirchHaakansson** [comment]
MadeUpData_for_SL_SA_tests_v1 - SSuseForCalculateZero == Y
 
MadeUpData_for_SL_SA_tests_v2 - SSuseForCalculateZero == N

in Data can be used for testing

**Comment by nmprista** [comment]
should be solved now
