### ISSUE TITLE
Define "verbose" and "strict" parameters for all exported functions?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#152]
Many of our functions have the "verbose" and "strict" parameters - should we add them to all functions so we have consistency?  (If so, we should use the same default values for them in all functions.)

**Comment by rix133** [comment]
"verbose" should be implemented for all **exported** functions as this is easily understandable waht it should do. For strict it is not so straightforward so we will add strict only in those functions where it is needed with propper parameter explanation.
