### ISSUE TITLE
Use the option "build = FALSE" if trouble when trying to install the updated package

### ISSUE THREAD

**Issue by nicolas-tku** [ices-tools-dev/RDBEScore#161]
When trying to install the updated library I was facing an issue regarding Rcmd.exe, I finally solved it with the following
`install_github("ices-tools-dev/RDBEScore@dev", build = FALSE)`

**Comment by nmprista** [comment]
you are a star! thanks! 

(It will be nice to add this to README)

**Comment by nicolas-tku** [comment]
README updated. I close the issue.
