### ISSUE TITLE
Merge dev developments into main after WGRDBES-EST 2023

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#163]
The main needs to be updated to the latest RDBES version 1.19.18
The dev needs some fixes so that it could be added to main:

- [x] All tests should pass
- [x]  Cleanup
  - [x]  #168 Remove unused functions
  - [x] Only export the relevant functions
  - [x] Remove unused data, e.g., data based on the old data model
- [x] #164
   -  Version update to 0.3.0 
    -  add description 
    -   Add authors
- [x] #181
   -  "calc-probs.Rmd"  
   -   "calc-zeroes.Rmd"                  
  - "estimating-rdbesdataobjects.Rmd"         
  -  "manipulating-rdbesdataobjects.Rmd" 
  -  `browseVignettes(package = "RDBEScore")` should work
        after `remotes::install_github("ices-tools-dev/RDBEScore@dev", build_vignettes = T)`

**Comment by KirstenBirchHaakansson** [comment]
We need to clean up before release

- [ ] Remove unused functions
- [ ] Only export the relevant functions
- [ ] Remove unused data, e.g., data based on the old data model

**Comment by KirstenBirchHaakansson** [comment]
Update the README with right links and so on

**Comment by rix133** [comment]
> Update the README with right links and so on

see also #161

**Comment by rix133** [comment]
`browseVignettes(package = "RDBEScore")` does not seem to work for me currently It seems to have to do with Rstudio issue: https://github.com/rstudio/rstudio/issues/1766 Anyway  
 - [ ] `browseVignettes(package = "RDBEScore")` should work
        after `remotes::install_github("ices-tools-dev/RDBEScore@dev", build_vignettes = T)`

**Comment by rix133** [comment]
dev merged to main #191
