### ISSUE TITLE
DESCRIPTION file needs update

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#164]
- [x] Version update to 0.3.0 
   - [x] Imports update remove dplyr
   - [x] add description 
   - [x]  Add authors

**Comment by nicholascarey** [comment]
>  Imports update remove dplyr

Do we want to do this? I know we want to minimise dependencies, but this will break some functions I wrote. 
@davidcurrie2001

**Comment by rix133** [comment]
ok, so we solved 
>Imports update remove dplyr

by not removing it

**Comment by nicholascarey** [comment]
Ok, 3.6.3 fails to build. It's actually only one test, and probably wouldn't be too difficult to fix but for now i've made minimum version 4.1 in DESCRIPTION. Updated everything else here. Someone with better knowledge of the package might want to expand the description. 

I'm not going to add everyone as an author myself! Please take a look and add yourself. I've made it alphabetical for now. You don't have to include email address if you don't want to.  I've made everyone there a contributor, but role can be [multiple things](https://r-pkgs.org/description.html#sec-description-authors-at-r), so feel free to change.

**Comment by nicholascarey** [comment]
Actually i think author (`"aut"`) is better than contributor.
