### ISSUE TITLE
Test data, Lohr & Lumley - license and referencing

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBEScore#166]
Are we certain that we can use the data in our 

- [x] Lohr, SDAResources package license
- [x] Lumley, survey package license
- [x] Create a reference for both

**Comment by nmprista** [comment]
SDAResources is under licence [GPL 2 ](https://choosealicense.com/licenses/gpl-2.0/) and[ GPL 3](https://choosealicense.com/licenses/gpl-3.0/). Differences between the two are at "patent" level ([comparison](https://choosealicense.com/appendix/)).

**Comment by nmprista** [comment]
2023/11/02: email sent to ices secretariat requesting support in this issue

**Comment by rix133** [comment]
[survey](https://cran.r-project.org/web/packages/survey/index.html) is licensed under:
>  License:	[GPL-2](https://cran.r-project.org/web/licenses/GPL-2) | [GPL-3](https://cran.r-project.org/web/licenses/GPL-3)

so it should be OK as licence of data finally is same as[RDBEScore](https://github.com/ices-tools-dev/RDBEScore/blob/main/LICENSE)

In general GPL v2 is simpler and has fewer restrictions about how the software can be used in hardware. It doesn’t explicitly address issues like patents and tivoization.

**Comment by rix133** [comment]
I think there is no issue with this

**Comment by rix133** [comment]
documented an referenced the data `devtools::check()` pass:
 0 errors ✔ | 0 warnings ✔ | 0 notes ✔ (if 2 not working vignettes are deleted) #181
