### ISSUE TITLE
Remove `@export` from functions which don't need to be public

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/RDBEScore#168]
When you do this add `@keywords internal` to the `roxygen` tags, which will mean the function and help documentation will not appear in the index (though i think you need to delete the `man` folder and run `roxygen` again to rebuild the documentation or it does not get removed).

**Comment by rix133** [comment]
I think most obsolete functions are now removed but should any of those also be removed from exports:
 - [ ] applyGenerateProbs
 - [ ] createTableOfRDBESIds
 - [ ] estim
 - [ ] estimMC
 - [ ] filterAndTidyRDBESDataObject
 - [ ] filterRDBESDataObject
 - [ ] findAndKillOrphans
 - [ ] fixSLids
 - [ ] generateMissingSSRows
 - [ ] generateNAsUsingSL
 - [ ] generateProbs
 - [ ] generateZerosUsingSL
 - [ ] getTablesInRDBESHierarchy
 - [ ] newRDBESDataObject
 - [ ] removeBrokenSpeciesListLinks
 - [ ] removeBrokenVesselLinks
 - [ ] removePrefixFromVarNames
 - [ ] runChecksOnSelectionAndProbs
I think if a function is not used in a vignette it should not be exported but the vignettes are currently incomplete #163

**Comment by rix133** [comment]
we can keep it as is
