### ISSUE TITLE
Changes to some Repo settings

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/RDBEScore#170]
@colinpmillar 

Hi Colin. There are some repo settings we need to change that are under your control, and also a couple of other questions. 

- We have added a `docs` folder (or will do soon) for use as a GitHub pages site. Can you please go to the repo Settings > Pages and select 'Deploy from branch'  and set main > docs as the source. 
- Main page of the repo has a link to `[sboxrdbes.ices.dk/](https://sboxrdbes.ices.dk/)` on the right side under 'About'. This is the old link, so needs updated. We can't see the 'gear' icon to edit this section so assuming only you can. 
- We are currently using GPL-3.0 license in the `DESCRIPTION`, and apparently at some point you made a license commit (though maybe this is just the default when you initialise the repo). Is this ok? Have you any knowledge about official ICES policy regarding appropriate licenses? 
- In the `DESCRIPTION` we have made you the maintainer, since the package is hosted on ICES github (R packages generally only have one official maintainer, at least when it comes to CRAN). Let us know if this is ok.

**Comment by colinpmillar** [comment]
Have given the team maintain access, hopefully this helps with the description

**Comment by colinpmillar** [comment]
Completely fine to change the license - the guidance is for an open source, this comes from DIG, I cant quite find the reference, but I am looking.

**Comment by colinpmillar** [comment]
I am happy to be the maintainer - I think this means that if you submit to CRAN it would need to be me that does this. But more than happy for one of you to take the role.

**Comment by nicholascarey** [comment]
Great. Thanks Colin. I changed the link on the main page, and website is live at [rdbes.ices.dk/](rdbes.ices.dk/). 

> I am happy to be the maintainer - I think this means that if you submit to CRAN it would need to be me that does this. But more than happy for one of you to take the role.

Yes that's true. Let's leave it for now and we will cross that bridge if we ever come to it!
