### ISSUE TITLE
generateMissingSSRows does not work on windows 

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#173]
All tests fail at _**test-generateMissingSSRows.R**_  on **R 4.3.1**  Windows with **dplyr_1.0.9** the whole sessioninfo is below.

**Error: 'join_by' is not an exported object from 'namespace:dplyr**

`sessionInfo()`

> R version 4.3.1 (2023-06-16 ucrt)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19045)
> 
> Matrix products: default
> 
> 
> locale:
> [1] LC_COLLATE=Estonian_Estonia.utf8  LC_CTYPE=Estonian_Estonia.utf8   
> [3] LC_MONETARY=Estonian_Estonia.utf8 LC_NUMERIC=C                     
> [5] LC_TIME=Estonian_Estonia.utf8    
> 
> time zone: Europe/Tallinn
> tzcode source: internal
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] crayon_1.5.1      vctrs_0.4.1       cli_3.3.0         RDBEScore_0.3.0   rlang_1.0.4      
>  [6] DBI_1.1.3         processx_3.7.0    purrr_0.3.4       generics_0.1.3    assertthat_0.2.1 
> [11] data.table_1.14.2 glue_1.6.2        prettyunits_1.1.1 rprojroot_2.0.3   pkgbuild_1.3.1   
> [16] ps_1.7.1          fansi_1.0.3       tibble_3.1.8      lifecycle_1.0.1   compiler_4.3.1   
> [21] dplyr_1.0.9       pkgconfig_2.0.3   rstudioapi_0.13   R6_2.5.1          tidyselect_1.1.2 
> [26] utf8_1.2.2        pillar_1.8.0      curl_4.3.2        callr_3.7.1       magrittr_2.0.3   
> [31] tools_4.3.1       withr_2.5.0       remotes_2.4.2

**Comment by davidcurrie2001** [comment]
Have you tried updating to the latest version of dplyr (v1.1.3)?

**Comment by rix133** [comment]
I’m quite sure that’s the thing but I like many others dealing also with genomic data want to install packages using[BiocManager](https://cran.rstudio.com/web/packages/BiocManager/readme/README.html#:~:text=Using%20the%20BiocManager%20package%20helps,packages%20from%20the%20appropriate%20release.) that should ensure that dependencies across all installed packages won’t break globally.

the easy way to solve this is to add a minimum version of dplyr to the DESCRIPTION file

**Comment by davidcurrie2001** [comment]
Agreed.  Let's use the latest version of dplyr as the minimum since the function is a fairly new addition to the package.  If its easy to re-write we can also look at removing the call to dplyr::join_by so that we can relax the dplyr minimum requirement.

**Comment by rix133** [comment]
so I made it not use the **dplyr::join_by**  also actually inner_join was needed instead of left_join as the following checks if the merge retains rows
