### ISSUE TITLE
doEstimationForAllStrata function

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#18]
I've created a doEstimationForAllStrata function to create estimates for all strata in an object of class RDBESRawObject - it would be good to get some feedback on the format of the output.  

The variance values only relate to the current level, but the estimates of mean/total use the estimates from the child levels as an input.  It would be good if there was an easy way to incorporate the variance from the child levels into the variance at a given level.

**Comment by nmprista** [comment]
not really all strata, but all stages (in future may include clustering)

**Comment by rix133** [comment]
the function is similar to #15  must decide which to develop further

**Comment by nmprista** [comment]
wgrdbes - consider the comments on #24
