### ISSUE TITLE
update vignettes

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#181]
- [x] "calc-probs.Rmd"  
  - [x]  "calc-zeroes.Rmd"                  
  - [x] "estimating-rdbesdataobjects.Rmd"         
  - [x] "manipulating-rdbesdataobjects.Rmd" 
  - [x] `browseVignettes(package = "RDBEScore")` should work
        after `remotes::install_github("ices-tools-dev/RDBEScore@dev", build_vignettes = T)`

**Comment by nmprista** [comment]
@rix133 I like your idea of splitting calc-zeros from calc-probs. Thinking of working on the 1st one tomorrow or are you doing work on it already?

**Comment by rix133** [comment]
no I'm not working on calc-zeros and calc-probs. I'm working on "estimating-rdbesdataobjects.Rmd" we can split into diffrent issues

**Comment by rix133** [comment]
Actually I think it was your idea to split the two (or somebody else) anyway I will deal with something else and leave fixing those two to you for now. Before commit check if they build `devtools::build_rmd("vignettes/calc-zeroes.Rmd")` `devtools::build_rmd("vignettes/calc-probs.Rmd")`

**Comment by nmprista** [comment]
Vignette for calculation of probabilities, re-worked in f6b67883952d8fe2c571006490786123a145b616

**Comment by rix133** [comment]
vignettes now build
