### ISSUE TITLE
applyGenerateProbs says stop if stratified/clustered but doesn't

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#187]
within applyGenerateProbs there are stop clauses for cases of stratification and clustering. These were misspecified (if-clause assumed no prefix but prefixes are now present)

**Comment by nmprista** [comment]
solved in 99a350282df9a7edd6cd0a91064bfd04ad8fb50c

**Comment by rix133** [comment]
@nmprista  there is only one test on `applyGenerateProbs` and it fails :)  Could you make at least 1 that that gives some kind of expected output

**Comment by nmprista** [comment]
tests now pass @rix133

**Comment by nmprista** [comment]
a simple test is added (more needed). will open a new issue.
