### ISSUE TITLE
estimMC function - use selection and inclusion probabilities instead of numSamp and numTotal?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#19]
Hi @rix133 I think it would be more flexible to use the selection and inclusion probabilities as parameters for estimMC, rather than numSamp and numTotal.  This would mean the function could be used for unequal probability sampling, as well as simple random sampling.  A separate function could be written to calculate the selection and inclusion probabilities in the case of simple random sampling.  

What do you think?

**Comment by davidcurrie2001** [comment]
Ok, estimMC now accepts selection and inclusion probs as parameters and uses them for UPSWR and UPSWOR.  I've written some simple tests for UP* where selection and inclusion probs are supplied however I've calculated these probability values based on simple random sampling.  We need to add more tests based on unequal probabilities to test this more thoroughly.

**Comment by KirstenBirchHaakansson** [comment]
Subgroup - we are not sure we totally get this and it would probably be much easier if someone else fixed this

**Comment by davidcurrie2001** [comment]
Done - needs more testing
