### ISSUE TITLE
CE & CL column names 

### ISSUE THREAD

**Issue by karolinamg** [ices-tools-dev/RDBEScore#193]
When loading these two files with createRDBESDataObject and transform them in a data frame 

df <- createRDBESDataObject(c("CEfile.zip", "CLfile.zip"))
CL <- as.data.frame(df["CL"])
CE <- as.data.frame(df["CE"])

the column names are returned as CL.XXX (e.g., CL.CLrecType). Is this intentional? 

The data used were the downloaded zip files from RDBES after the most recent datacall and the RDBEScore version is 0.3.0.

**Comment by karolinamg** [comment]
The single brackets are causing this. If two brackets are used the correct column names are returned
CL <- as.data.frame(df[["CL"]])
CE <- as.data.frame(df[["CE"]])

**Comment by davidcurrie2001** [comment]
Both of these are are ways of subsetting. The single bracket [] will return a subset of the list, which in itself will be a list. i.e., It may or may not contain more than one elements. On the other hand, a double bracket [[]] will return just a single element from the list.  An RDBESDataObject is essentially a list of data.tables so if you want a single element from the RDBESDataObject then you should use the double bracket. 

This is standard R behaviour so I don't think we need to document it.  Closing - please re-open if required.
