### ISSUE TITLE
Test renameSpeciesSA function in WGRDBES-EST/personal/Kasia/renameSpeciesSA.R

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#199]
We need to test the renameSpeciesSA function to ensure it correctly renames species codes in the SA table based on the species list in SL and add it to the main code base.

See also  #177  #176

Recent Changes:

Commit 664a41a: vignette renameSA by [Kasia-MIR](https://github.com/Kasia-MIR).
Commit 08607c3: #86 #177 by [Kasia-MIR](https://github.com/Kasia-MIR).
Function Definition:

You can view the file [here](https://github.com/ices-tools-dev/RDBEScore/blob/dev/WGRDBES-EST/personal/Kasia/renameSpeciesSA.R).

Tasks:

Run the renameSpeciesSA function with sample data.
Validate the output to ensure species codes are correctly renamed.
Report any issues or unexpected behavior.
Let's proceed with creating this issue in the repository.

**Comment by davidcurrie2001** [comment]
I have moved the function to the R folder and started to write tests

**Comment by davidcurrie2001** [comment]
Updated vignette and added it to the package
