### ISSUE TITLE
Define verbose = FALSE to all exported functions

### ISSUE THREAD

**Issue by rix133** [ices-tools-dev/RDBEScore#200]
As decided in #152 all functions need exported verbose parameter these are:
Here are the names and links to the functions in the `ices-tools-dev/RDBEScore` repository:

- [x] [applyGenerateProbs](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/applyGenerateProbs.R)
- [x] [combineRDBESDataObjects](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/combineRDBESDataObjects.R)
- [x] [createRDBESDataObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/createRDBESDataObject.R)
- [x] [createRDBESEstObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/createRDBESEstObject.R)
- [ ] [createTableOfRDBESIds](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/createTableOfRDBESIds.R)
- [x] [doEstimationForAllStrata](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/doEstimationForAllStrata.R)
- [x] [estim](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/estim.R)
- [x] [estimMC](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/estimMC.R)
- [x] [filterAndTidyRDBESDataObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/filterAndTidyRDBESDataObject.R)
- [x] [filterRDBESDataObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/filterRDBESDataObject.R)
- [x] [findAndKillOrphans](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/findAndKillOrphans.R)
- [x] [fixSLids](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/fixSLids.R)
- [x] [generateMissingSSRows](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/generateMissingSSRows.R)
- [x] [generateNAsUsingSL](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/generateNAsUsingSL.R)
- [x] [generateProbs](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/generateProbs.R)
- [x] [generateZerosUsingSL](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/generateZerosUsingSL.R)
- [x] [getTablesInRDBESHierarchy](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/getTablesInRDBESHierarchy.R)
- [x] [newRDBESDataObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/newRDBESDataObject.R)
- [x] [removeBrokenSpeciesListLinks](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/removeBrokenSpeciesListLinks.R)
- [x] [removeBrokenVesselLinks](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/removeBrokenVesselLinks.R)
- [ ] [removePrefixFromVarNames](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/removePrefixFromVarNames.R)
- [x] [runChecksOnSelectionAndProbs](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/runChecksOnSelectionAndProbs.R)
- [x] [validateRDBESEstObject](https://github.com/ices-tools-dev/RDBEScore/blob/main/R/validateRDBESEstObject.R)

**Comment by davidcurrie2001** [comment]
Checked the functions listed above.  We might want to delete the removePrefix function (#204 ) and not export the createTableofRDBESIDs function (#205 )
