### ISSUE TITLE
How to handle species selection (SS) within estimation?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#21]
I was wondering how to handle the SS table during estimation?  Currently I'm not using it for estimation e.g. if I want to estimate the amount of cod discards it doesn't seem to make sense to me to raise the cod estimates to the number of different species that were present in the haul.

Are there any cases when we would want to include SS in the estimation?  E.g. trying to estimate the total amount of all discards, irrespective of species?

**Comment by davidcurrie2001** [comment]
This issue is similar to #20

**Comment by nmprista** [comment]
With regards to ratio estimators, there are plenty of situations where discards of a certain species are raised to target species or groups of other species. 

With regards to unbiased estimators of totals or means other species are not needed assuming 0s have already been included (i.e., you are using the prepObj) only the values of that species and the probabilities/weights of the samples will suffice for estimation. 

In data "shrimps.Rdata" I have handled the SS in a way that should make it simple to always have it included by default in the estimObj without much additional work.

**Comment by davidcurrie2001** [comment]
Discussion at meeting on 9/9/22 - generally people probably won't want to use the SS numbers/probabilities to raise the data.  Often a census will be taken at the SS level in which case it doesn't matter anyway.  However it should be possible to use the SS numbers/probabilities to raise the data if somebody needs to do that.

**Comment by nmprista** [comment]
wgrdbes-est 2022: lets try with a general default and see.

**Comment by davidcurrie2001** [comment]
SS sampling variables should be respected when they are present.  Normally the SS will be a census but when it is not it is up to the user to decide if their data is correct.
