### ISSUE TITLE
importRDBESDownloadData returns 0 row data tables for optional tables

### ISSUE THREAD

**Issue by karolinamg** [ices-tools-dev/RDBEScore#36]
importRDBESDownloadData  returns 0 row data tables (hierarchy 5) for optional tables (e.g. FishingTrip) that only contain column names when exported from RDBES instead of NULL and the validateRDBESRawObject function returns TRUE.

**Comment by rix133** [comment]
rather change the validation to raise a warning if some optional tables have 0 rows
