### ISSUE TITLE
Rename icesRDBES to RDBEScore

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#37]
wgrdbes-est 2022 decided that icesRDBES was too general a name. Also, there was advantage is moving into RDBESvisualise the visualisation tools requiring more dependencies. Decision was made to use the name "RDBEScore" so as to include the core functions for import, preparation and estimation.

**Comment by rix133** [comment]
done both for dev [4db24834f22](https://github.com/ices-tools-dev/RDBEScore/commit/6e91db284be30fbca2f985efbe6094db24834f22) and main [d51def5f](https://github.com/ices-tools-dev/RDBEScore/commit/0be17ede2f96040e1376b4950defe512d51def5f)  branch
