### ISSUE TITLE
Create RDBESvisualise package

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#38]
wgrdbes-est 2022: decided that graphical functions should be in a separate package called "RDBESvisualise" to avoid dependencies in main package. [Fish&Co directory ](https://github.com/ices-tools-dev/icesRDBES/tree/main/FishNCo)needs to be migrated to this new package.

**Comment by davidcurrie2001** [comment]
Created initial package structure in https://github.com/ices-tools-dev/RDBESvisualise and copied FishNCo directory to there.

**Comment by colinpmillar** [comment]
Would you like this built and tested for windows and mac osx on the r universe site? https://ices-tools-prod.r-universe.dev/builds

**Comment by davidcurrie2001** [comment]
> Would you like this built and tested for windows and mac osx on the r universe site? https://ices-tools-prod.r-universe.dev/builds

@colinpmillar  Yes - that would be great.  There's only a hello world function in the package at the moment so its not urgent though.

**Comment by sykan** [comment]
At long last, I thought of doing the FishNCo  $\rightarrow$ RDBESVisualise dir migration but noticed David already did this. 
Many thanks for your effort, David! And sincere apologies for not doing this despite what I promised. 
I'll try my best to familiarize myself with the current content of visualise-package.

**Comment by davidcurrie2001** [comment]
@sykan No problem.  I have migrated the landings and effort coverage functions into 5 coveragexxx() functions in the Dev branch of RDBESvisualise - there is a vignette to show how they work using some test data.  I've tried to re-factor and improve the code as I went along.

**Comment by nmprista** [comment]
package has been created - issue closed 

@anacfernandes @erosquesada discussion above might still interest you
