### ISSUE TITLE
Consolidate `createRDBESDataObject` and `importRDBESDownloadData`

### ISSUE THREAD

**Issue by nicholascarey** [ices-tools-dev/RDBEScore#39]
These two functions seem to do a very similar task and could be consolidated to one function?

Three kinds of main input:
- zip file downloaded from RDBES 
    - should be able to recognise .zip file extension and import without any other inputs
- folder of files downloaded from RDBES and unzipped with correct filenames as determined by RDBES 
    - should be able to recognise filenames 
- folder of csv files created by user
    - the `listOfFileNames` input would be required *unless* they have the official RDBES names

Are there other cases? I believe David's code covers most of the above cases at present, but split across these two functions.

**Comment by davidcurrie2001** [comment]
For S3 classes the following is recommended by [Advanced R](https://adv-r.hadley.nz/s3.html):
"R doesn’t stop you from shooting yourself in the foot, but as long as you don’t aim the gun at your toes and pull the trigger, you won’t have a problem.
To avoid foot-bullet intersections when creating your own class, I recommend that you usually provide three functions:
- A low-level constructor, **new_myclass()**, that efficiently creates new objects with the correct structure.
- A validator, **validate_myclass()**, that performs more computationally expensive checks to ensure that the object has correct values.
- A user-friendly helper, **myclass()**, that provides a convenient way for others to create objects of your class."

**Comment by nicholascarey** [comment]
Well, I would say the first and third are redundant to each other ¯\\_(ツ)_/¯

If they are to be separate I think it needs to be more clear in the documentation what they are for. 

`createRDBESDataObject` says: 
```
"#' Create an R object from a folder containing .csv data files downloaded from the RDBES upload/download page." 
```

`importRDBESDownloadData` says: 
```
#' Read the .zip files and/or .csv files downloadable from the ICES RDBES web page. 
```

Maybe I'm not seeing the distinction?

It's not a big deal, just a little confusing for new users unsure about which to use.

**Comment by davidcurrie2001** [comment]
I agree that they should be consolidated - should the consolidated function be named RDBESDataObject() to follow the S3 naming pattern?  I think that would make sense.

**Comment by nicholascarey** [comment]
> I agree that they should be consolidated - should the consolidated function be named RDBESDataObject() to follow the S3 naming pattern? I think that would make sense.

Yeah, sounds reasonable

**Comment by ptrptr** [comment]
Also note the existing function newRDBESDataObject.  With validateRDBESDataObject we are only missing the RDBESDataObject function (and snake_case 🐍). Consolidating the two functions create* and import* to RDBESDataObject() seems sensible.

**Comment by anacfernandes** [comment]
Gives an error importing zip files:

Warning message:
In RDBEScore::createRDBESDataObject(tmp, castToCorrectDataTypes = castToCorrectDataTypes) :
  No relevent files found in given directory - an empty object will be created"

But it imports data ok, if tables are not in a zip file.

**Comment by rix133** [comment]
I would go with renaming the `importRDBESDownloadData` to `importRDBESDataObject` and making `createRDBESDataObject`  private (ie. not exported) the `importRDBESDownloadData` is just a wrapper around `createRDBESDataObject` that enables to directly import the `.zip ` file of downloaded data without extracting it beforehand into a folder somewhere

**Comment by rix133** [comment]
> Possibly allow a RDBES file to be created from data.frames or a list object already within R?
https://github.com/ices-tools-dev/RDBEScore/commit/cca2451efaab0660e352067f9f87ca2b5b7fdbf4

**Comment by nicholascarey** [comment]
I can work on this. Just so I'm sure i have it correct, there will be two new functions: 

`importRDBESDataObject`  - consolidates `importRDBESDownloadData` (which is effectively moved into this function) and `createRDBESDataObject`  (which is made private/internal) to a function that imports both zip files and folder of csv files. 

A new function based on Richard's draft to create an RDBES object from a list of `data.frames`. Re-using the name `createRDBESDataObject` for this makes sense? (i would rename it first to something else before using it for this new function).

**Comment by rix133** [comment]
I think there should be only 1 public import/create function: `importRDBESDownloadData` renamed to  `importRDBESData` 
and it would also should import a list of data frames 
What others think?

**Comment by davidcurrie2001** [comment]
As a reminder, S3 naming convention for constructors: https://adv-r.hadley.nz/s3.html#s3-classes

**Comment by nicholascarey** [comment]
Ok, consensus seems to  one function `createRDBESDataObject` which covers importing a zip file, a folder of csv's, or a list of data frames.  Myself and @karolinamg can work on this.

**Comment by nicholascarey** [comment]
Complete. `createRDBESDataObject` now accepts zip files, csv, or list of data frames. Previous functions have been renamed and made internal.  I will do some more testing, but otherwise closing this issue.
