### ISSUE TITLE
Does createRDBESEstObject produce the correct output when sub-sampling is present?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#48]
Does createRDBESEstObject produce the correct output when sub-sampling is present?  It passes the current, limited tests but I'm not convinced that the output is correct when data is present at multiple levels of sub-sampling.

**Comment by KirstenBirchHaakansson** [comment]
I will try to test this with some Danish herring data where we have FM on the 1st level of subsampling and BV on the 2nd level of subsampling

1st step would be to upload a small herring data set

**Comment by nicolas-tku** [comment]
I've tried on 2021 herring data from Finland, seems to give the correct output

**Comment by KirstenBirchHaakansson** [comment]
I will like to work with the sub-sampling issue, so will create a small test dataset with subsampling. The test data will be created so it is possible to add more cases of subsampling

**Comment by davidcurrie2001** [comment]
SAparentID used to be used to link samples and sub-samples - it is not used any more and is not in the RDBES data download.  SAseqNum and SAparSeqNum are now used to link SA records.  I have removed SAparentID from the RDBESEstObject.

**Comment by rix133** [comment]
@davidcurrie2001  is this done? or are still new tests needed

**Comment by davidcurrie2001** [comment]
It seems to be working ok - closing for now.  We can re-open if problems are discovered.
