### ISSUE TITLE
Add dataset example 3.2 and 3.6 Lohr 

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#50]
Create an RDBES test dataset with example 3.2 and 3.6 of Lohr to be used in testing estimation functions

**Comment by nmprista** [comment]
dataset uploaded to RDBES as H1 with SDcountry==ZW, DEyear = 1992. 
download from RDBES is available in data in [ad73fe9](https://github.com/ices-tools-dev/icesRDBES/commit/ad73fe9b9e67c27f5711e3b5028bccddc7b61d54) 
Documentation is needed

**Comment by KirstenBirchHaakansson** [comment]
Cool :-) - did you use the SDAResources package. It has Lohr datasets from the 3rd edition of the book with a public license, so it should be ok to use these

**Comment by anacfernandes** [comment]
Moved to data_raw; decided not need to document; it comes from that package.

**Comment by nmprista** [comment]
useful to fix the dummy numTotal, numSampled and probs to 1 in original data
