### ISSUE TITLE
Should our functions update the RDBES object's data tables by reference?

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#52]
We are using data.table as an underlying data structure - this is optimised for large data sets and the data.table package functions often update their parameters by reference i.e. a data.table that is passed as a parameter to the function is actually altered.  This avoids having to create a copy of a potentially large object.  https://cran.r-project.org/web/packages/data.table/vignettes/datatable-reference-semantics.html

Our functions don't do this - they don't alter the input parameters, they return a new object.  Should we change our functions to update by reference?  

If we use this approach rather than coding
`
myFilteredObject <- filterRDBESDataObject(myH1RawObject, fieldsToFilter = myFields, valuesToFilter = myValues )
`
and getting a new filtered object called _myFilterObject_, we would instead write
`
filterRDBESDataObject(myH1RawObject, fieldsToFilter = myFields,  valuesToFilter = myValues )
`
and _myH1RawObject_ would be filtered.

**Comment by ptrptr** [comment]
Maybe return the first argument as return(invisible(firstArgument)) anyway? This way the pipe operator should still work.

**Comment by davidcurrie2001** [comment]
Discussed at inter-sessional meeting 17/11.  Consensus was that we should leave the functions' behaviour as it is at the moment - however if we run into performance issues with large data sets we might need to re-visit this question.
We should also add tests to check that the input parameters to our functions are not being changed - at least for the functions that make use of data.table.
