### ISSUE TITLE
findAndKillOrphans and removeBrokenSpeciesListLinks need integration into filterRDBESdataObject

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#58]
At present when data is filtered and `findAndKillOrphans `is run, SL remains untouched. 

`removeBrokenSpeciesListLinks `needs to be run after it to fix the unused species lists.
Same thing for `removeBrokenVesselLinks` with regards to vessels

Ideally the last two functions would be integrated into the `filterRDBESdataObject` with default behavior `TRUE.`

**Comment by davidcurrie2001** [comment]
Related to #62

**Comment by KirstenBirchHaakansson** [comment]
Closed - will be solved with #62
