### ISSUE TITLE
Large interger in general

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-tools-dev/RDBEScore#61]
Running the validateRDBESDataObject I get a 'NAs introduced by coercion to integer range'. This is caused by a very large numeric value.

From as.integer doc
"Note that current implementations of R use 32-bit integers for integer vectors, so the range of representable integers is restricted to about +/- 2*10^9 : doubles can hold much larger integers exactly.

**Comment by KirstenBirchHaakansson** [comment]
Suggested solution: fields that in genral can hold very large numbers should be double in mapColNamesFieldR

**Comment by nicholascarey** [comment]
Potentially use `round(as.double(column))` instead of `as.integer` for some columns.

**Comment by KirstenBirchHaakansson** [comment]
What if you want to join to datasets one with the field as integer and one with double - then you would need to decide and I would normally just pick as.integer -> same problem as before

**Comment by nicholascarey** [comment]
In that case the new column will become `double`. Same values, just in scientific notation. It should not affect numeric operations...

**Comment by KirstenBirchHaakansson** [comment]
Great, then I think you have the solution

**Comment by nicholascarey** [comment]
New internal function called `as.integer.or.dbl` added, and used in `setRDBESDataObjectDataTypes`. Tests added too. 

9852bbd5833889edf471f736913c9999289e7bc9

**Comment by nicholascarey** [comment]
Seems to have caused no issues.
