### ISSUE TITLE
importRDBESDownloadData overwrites common tables when importing two different hierarchies 

### ISSUE THREAD

**Issue by karolinamg** [ices-tools-dev/RDBEScore#65]
importRDBESDownloadData overwrites common CS tables when importing multiple zip files that contain different hierarchies.

**Comment by karolinamg** [comment]
Throw an error when there are common names in different zip files. Update the documentation of the  importRDBESDownloadData function.

**Comment by nmprista** [comment]
discussed meeting 2022-11-17 - unclear if it is solved - to be investigated

**Comment by nicholascarey** [comment]
Could be resolved by not allowing multiple zip files to be imported. Any combining of different (or the same) hierarchies seems outside the scope of this function. 

@rix133 do you agree? Talking in the room we were unsure why someone would want to import multiple zip files (or hierarchies) in a single operation.

**Comment by nicholascarey** [comment]
`createRDBESDataObject` allows multiple zip file to be imported, e.g. H1 and CL/CE, in which case these will overwrite the ones in H1.
