### ISSUE TITLE
Include missing hierarchies in ChecksOnSelectionAndProbs

### ISSUE THREAD

**Issue by anacfernandes** [ices-tools-dev/RDBEScore#7]
Functions are only working for upper hierarchies 1 and 7, and lower hierarchy C.
Future adaptation of the code will be needed to work with the missing hierarchies.

**Comment by nmprista** [comment]
wgrdbes-est 2022: issue tracked down to run ChecksOnSelectionAndProbs. Function needs improvement.

**Comment by davidcurrie2001** [comment]
ChecksOnSelectionAndProbs() has no restrictions on upper or lower hierarchies now, although there are still some features within the function that need further developing.
