### ISSUE TITLE
create a map of RDBES CL data

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#79]

**Comment by davidcurrie2001** [comment]
Ultimately this will be included in a different package - this is related to issue #38

**Comment by davidcurrie2001** [comment]
The coverageLandings() function has now been added to the dev branch of the RDBESvisualise package https://github.com/ices-tools-dev/RDBESvisualise - this compares landings to sample data.

**Comment by KirstenBirchHaakansson** [comment]
this belong to RDBESvisualise
