### ISSUE TITLE
New function "createTableOfRDBESIds" needs to be adapted for more hierarchies

### ISSUE THREAD

**Issue by anacfernandes** [ices-tools-dev/RDBEScore#82]
The function is used in the `generateZerosUsingSL` and in `test-generateZerosUsingSL`. It is only working for hierarchies 1 and 5. Need to adapt the code for the other higher and lower hierarchies.

**Comment by davidcurrie2001** [comment]
You could make use of the existing getTablesInRDBESHierarchy.R function to widen the number of hierarchies it works for.

**Comment by nmprista** [comment]
By the looks of https://github.com/ices-tools-dev/RDBEScore/pull/87/commits/3ae75fc1bd065433afe8b557623293a23a38ebc2 this issue can be closed. @karolinamg is testing.
