### ISSUE TITLE
create an html map of RDBES CS data

### ISSUE THREAD

**Issue by nmprista** [ices-tools-dev/RDBEScore#83]
Discussed in Tartu 2022 - would be nice to have a html map for RDBES similat to the one fishNCo developed for estimates.

**Comment by davidcurrie2001** [comment]
The coverageLandings() function has now been added to the dev branch of the RDBESvisualise package https://github.com/ices-tools-dev/RDBESvisualise - this compares landings to sample data.

**Comment by rix133** [comment]
As this is now on `RDBESvisualise` closing here
