### ISSUE TITLE
Please be courteous when commenting in code/issues

### ISSUE THREAD

**Issue by davidcurrie2001** [ices-tools-dev/RDBEScore#88]
Can we please be courteous when making comments about other people's code e.g. I don't think comments like the following are particularly helpful "_implement content, type checks using stop and fix this mess_" - an alternative would be to say "_implement content, type checks using stop and make this more readable / tidy this up/ make it more efficient_"

Of course, you can still be as rude about your own code as you like...

**Comment by davidcurrie2001** [comment]
Actually, thinking about it perhaps we should just be polite about all of **_our_** code.  That doesn't mean we shouldn't identify where things can be improved but we should be thoughtful about how we say it.

**Comment by davidcurrie2001** [comment]
@nmprista @KirstenBirchHaakansson Raise this in the next plenary meeting and also include in Newbies Guide?

**Comment by nmprista** [comment]
We will. Thanks @davidcurrie2001 .
